before_script:
   - apt update -qq && apt install -y -qq cmake git-core wget make
     libboost-dev libgmp-dev swig gcc gfortran g++ liblapack-dev
     libatlas-base-dev lp-solve liblpsolve55-dev python3-dev
     libpython3-dev bash swig doxygen python3-dev python3-pip graphviz htop



install_siconos:
  stage: build
  image: ubuntu:17.10
  script:
    - "sh ci/install_siconos.sh"
  artifacts:
    paths:
      - install-siconos
  only:
  - master


build_and_run_examples:
  stage: build
  image: ubuntu:17.10
  script:
    - "sh ci/build_examples.sh"
  artifacts:
    paths:
      - build-examples
  only:
  - master
  dependencies:
   - install_siconos  
  

run_examples:
  stage: test
  image: ubuntu:17.10
  script:
    - "sh ci/run_examples.sh"
  only:
  - master
  dependencies:
   - build_and_run_examples
