image: ubuntu:17.10

cache:
    paths:
    - .apt/
    

before_script:
   # Configure apt chaching
   - echo $CI_PROJECT_DIR
   - export APT_DIR=$CI_PROJECT_DIR/.apt && export APT_STATE_LISTS=$APT_DIR/lists && export APT_CACHE_ARCHIVES=$APT_DIR/archives
   - printf "dir::state::lists    ${APT_STATE_LISTS};\ndir::cache::archives    ${APT_CACHE_ARCHIVES};\n" > /etc/apt/apt.conf
   - mkdir -p "${APT_STATE_LISTS}/partial" && mkdir -p "${APT_CACHE_ARCHIVES}/partial"
   - apt update -qq && apt install -y -qq cmake git-core wget make
     libboost-dev libgmp-dev swig gcc gfortran g++ liblapack-dev
     libatlas-base-dev lp-solve liblpsolve55-dev python3-dev
     libpython3-dev bash swig doxygen python3-dev python3-pip htop
     libcppunit-dev python3-scipy



install_siconos:
  stage: build
  script:
    - "sh ci/install_siconos.sh"
  artifacts:
    paths:
      - install-siconos
  only:
  - master


build_and_run_examples:
  stage: test
  script:
    - "sh ci/build_examples.sh"
  artifacts:
    paths:
      - build-examples
  only:
  - master
  dependencies:
   - install_siconos  
  

run_examples:
  stage: deploy
  script:
    - "sh ci/run_examples.sh"
  only:
  - master
  dependencies:
   - build_and_run_examples
